routes/web.php
<?php

use App\Http\Controllers\Admin\AllergenController;
use App\Http\Controllers\Admin\CategoryController;
use App\Http\Controllers\Admin\DishController;
use App\Http\Controllers\Admin\MenuController;
use App\Http\Controllers\Admin\TypeController;
use App\Http\Controllers\PublicController;
use Illuminate\Support\Facades\Route;

use App\Http\Controllers\Admin\AdminController;


/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

// PARTE PÚBLICA

/*
 * HOME
 */

//Route::get('/', function () {
//    $title = "Inicio";
//    return view('home', compact('title'));
//})->name('home');

Route::get('/', [PublicController::class, 'index'])->name('home');

Route::get('/menu', [PublicController::class, 'menu'])->name('menu');


/*
 * Acceso a Administración
 */
Route::get('login_empresa', function () {
    return view('auth.login');
})->name('login_empresa');


//Auth::routes();

// PARTE ADMINISTRACIÓN

Route::middleware(['auth:sanctum', 'verified'])->get('/dashboard', function () {
    return view('dashboard');
})->name('dashboard');


Route::group(['middleware' => ['auth']], function () {

    Route::get('admin/printMDia', [AdminController::class, 'printMDia'])->name('admin.printMDia');
    Route::get('admin/printMDegus', [AdminController::class, 'printMDegus'])->name('admin.printMDegus');

    Route::get('/admin', [AdminController::class, 'index'])->name('admin');

    Route::resource('/admin/allergens', AllergenController::class);

    Route::resource('/admin/categories', CategoryController::class);

    Route::resource('/admin/types', TypeController::class);

    Route::resource('/admin/dishes', DishController::class);

    //Route::get('menus/selectDishes', [MenuController::class, 'selectDishes'])->name('menu.selectDishes');


    Route::post('menus/selectDishes', [MenuController::class, 'storeDish'])->name('menus.storeDish');
    Route::put('menus/updateDishes', [MenuController::class, 'updateDish'])->name('menus.updateDish');

    Route::resource('/admin/menus', MenuController::class);


});

app/Models/Menu.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Menu extends Model
{
    use HasFactory;

    //protected $fillable = ['name', 'price', 'description'];

    //aquí guardamos los campos que queremos evitar que se llenen por asignación masiva
    protected $guarded = ['id', 'created_at', 'updated_at'];

    //Relación muchos a muchos

    public function categories(){
        return $this->belongsToMany(Category::class,'category_dish_menu')
            //->withPivot('dish_id', 'status');
            ->withPivot('dish_id');
    }

    public function dishes(){
        return $this->belongsToMany(Dish::class,'category_dish_menu')
            //->withPivot('category_id', 'status');
            ->withPivot('category_id');
    }


    //Relación uno a muchos inversa
    public function type(){
        return $this->belongsTo(Type::class);
    }


    public function platos()
    {
        return $this->hasManyThrough(Dish::class, Category::class);
    }

}

app/Http/Controllers/Admin/MenuController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use App\Models\Category;
use App\Models\Dish;
use App\Models\Menu;
use App\Models\Type;
use Carbon\Carbon;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\DB;
use phpDocumentor\Reflection\Types\Integer;

class MenuController extends Controller
{
    protected $paginationTheme = 'bootstrap';

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index(Request $request)
    {
        $titlePage = "Gestión de Menús";
        $title = "Menús";

        $menus = Menu::where([
            [
                function ($query) use ($request) {
                    if (($term = $request->term)) {
                        $query->orWhere('name', 'LIKE', '%' . $term . '%')->get();
                    }
                }
            ]
        ])
            ->paginate(4);

        return view('admin.menus.index', compact('menus', 'titlePage', 'title'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $titlePage = "Creación de Menús";
        $title = "Crear menú";
        //$categories = Category::pluck('name', 'id');
        $categories = Category::all();
        $types = Type::pluck('name', 'id');
        //$dishes = Dish::pluck('name', 'id');

        //return view('admin.menus.create', compact('titlePage', 'title', 'categories', 'types', 'dishes'));
        return view('admin.menus.create', compact('titlePage', 'title', 'categories', 'types'));

    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //dd($request->all());
        $request->validate([
            'type_id' => 'required',
            'categories' => 'required'
        ]);

        $menu = new Menu();

        $menu->description = $request->description;
        if($request->price){
            $menu->price = str_replace(',', '.', $request->price);
        }
        if($request->dateMenu){
            $menu->dateMenu = Carbon::createFromFormat('d/m/Y', $request->dateMenu);
        }
        $menu->type_id = $request->type_id;
        $menu->save();

        $categories = $request->categories;
        $numCategories = count($categories);

        $selectedCategories = [];
        $data = [];

        for ($i = 0; $i < $numCategories; $i++) {
            //dd($categories[$i]);
            $data = DB::table('categories')
                ->select('id', 'name')
                //->select('name')
                ->where('id', $categories[$i])
                //->get();
                ->first();

            array_push($selectedCategories, $data);
        }

        $titlePage = "Selección de Platos";
        $title = "Menú";
        $dishes = Dish::pluck('name', 'id');

        $editar = 0;

        //dd($menu->id);

        //return view('admin.menus.selectDishes', compact('titlePage','title', 'idMenu', 'categories', 'dishes'));
        //return view('admin.menus.selectDishes', compact('titlePage','title', 'menu', 'categories', 'numCategories', 'dishes'));
//        return view('admin.menus.selectDishes',
//            compact('titlePage', 'title', 'menu', 'numCategories', 'selectedCategories', 'dishes'));
//
        return view('admin.menus.selectDishes',    compact('titlePage', 'title', 'menu', 'numCategories', 'selectedCategories', 'dishes', 'editar'));

    }


    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request $request
     * @return \Illuminate\Http\Response
     */
    public function storeDish(Request $request)
    {
        //dd($request->all());

        $menu = Menu::find($request->menu_id);

        for ($i = 0; $i < $request->numCategories; $i++) {

            if ($request->has('dishes_' . $request->categories_name[$i])) { //si true

                //dd($request->all($request->name = 'dishes_' . $request->categories_name[$i]));
                $dishes = $request->all($request->name = 'dishes_' . $request->categories_name[$i]);

                //$num_platos = count($dishes);
                $num_platos = count($dishes['dishes_' . $request->categories_name[$i]]);

                //dd('NumPlatos:'.$num_platos);

                for ($j = 0; $j < $num_platos; $j++) {
                    $idDish = $dishes['dishes_' . $request->categories_name[$i]][$j];
                    //dd('IdPlato: '.$idDish);

                    $menu->dishes()->attach($idDish, ['category_id' => $request->categories_id[$i]]);
                }
            }
        }

        return redirect()->route('menus.index')
            ->with('info', 'Menú creado con éxito.');
    }


    /**
     * Display the specified resource.
     *
     * @param  int $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }


    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Models\Menu $menu
     * @return \Illuminate\Http\Response
     */
    public function edit(Menu $menu)
    //public function edit(Integer $idMenu)
    {
        $titlePage = "Edición de Menús";
        $title = "Editar menú";

        $categories = Category::all();
        $types = Type::pluck('name', 'id');

        //si hay dateMenu
        if($menu->dateMenu){
            $dateMenu = date('d/m/Y', strtotime($menu->dateMenu));
        }else{
            $dateMenu = $menu->dateMenu;
        }

        //dd($dateMenu);
        return view('admin.menus.edit', compact('menu', 'titlePage', 'title', 'categories', 'types', 'dateMenu'));

    }


    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request $request
     * @param  \App\Models\Menu $menu
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Menu $menu)
    {
        $request->validate([
            'type_id' => 'required',
            'categories' => 'required'
        ]);

        $menu->description = $request->description;
        if($request->price){
            //reemplazamos si hay coma en el precio por .
            $menu->price = str_replace(',', '.', $request->price);
        }

        if($request->dateMenu){
            $menu->dateMenu = Carbon::createFromFormat('d/m/Y', $request->dateMenu);
        }

        $menu->type_id = $request->type_id;
        $menu->update();

        $categories = $request->categories;
        $numCategories = count($categories);

        $selectedCategories = [];
        $data = [];

        for ($i = 0; $i < $numCategories; $i++) {

            $data = DB::table('categories')
                ->select('id', 'name')
                ->where('id', $categories[$i])
                ->first();

            array_push($selectedCategories, $data);
        }

        $titlePage = "Actualización de Platos";
        $title = "Menú";

        //Obtenemos todos los platos por si quiere añadir
        $dishes = Dish::all('name', 'id');

        //Aquí guardaremos los platos del menu y la categoría
        $dishes_menu = [];

        //Obteniendo las categorías asociadas al menu
        foreach ($categories as $category) {

            $dishesDB = DB::table('category_dish_menu')
                ->select('dish_id', 'category_id')
                ->where('menu_id','=', $menu->id)
                ->where('category_id', '=', $category)
                ->get();

            $d = $dishesDB->toArray();

            //Añadimos los platos de la categoria y el menu
            array_push($dishes_menu, $d);
        }

        $editar = 1;

        return view('admin.menus.updateDishes', compact('titlePage', 'title', 'menu', 'numCategories',
            'selectedCategories', 'dishes', 'dishes_menu', 'editar'));

    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request $request
     * @param  \App\Models\Menu $menu
     * @return \Illuminate\Http\Response
     */
    public function updateDish(Request $request, Menu $menu)
    {
        //dd($request->all());

//        $request->validate([
//            //'type_id' => 'required'
//            //'name' => 'required',
//            //$tipo
//        ]);

        //$menu->update($request->all());
        $menu = Menu::find($request->menu_id);

        for ($i = 0; $i < $request->numCategories; $i++) {

            if ($request->has('dishes_' . $request->categories_name[$i])) { //si true

                //dd($request->all($request->name = 'dishes_' . $request->categories_name[$i]));
                $dishes = $request->all($request->name = 'dishes_' . $request->categories_name[$i]);

                //$num_platos = count($dishes);
                $num_platos = count($dishes['dishes_' . $request->categories_name[$i]]);

                //dd('NumPlatos:'.$num_platos);

                for ($j = 0; $j < $num_platos; $j++) {
                    $idDish = $dishes['dishes_' . $request->categories_name[$i]][$j];
                    //dd('IdPlato: '.$idDish);
                    //dd($request->categories_name[$i]);

                    $dishExist = DB::table('category_dish_menu')
                        ->select('dish_id')
                        ->where('menu_id','=', $menu->id)
                        ->where('category_id', '=', $request->categories_name[$i])
                        ->where('dish_id', '=', $idDish)
                        ->get();

                    //dd($dishExist);
                    //if ($dishExist != $idDish) { //si el plato no es el mismo que hay, añado a BD
                    if(count($dishExist) >= 1) {
                        $menu->dishes()->attach($idDish, ['category_id' => $request->categories_id[$i]]);
                    }

resources/views/admin/menus/create.blade.php
<?php
/**
 * Created by PhpStorm.
 * User: Starglob2
 * Date: 27/04/2021
 * Time: 13:29
 */
?>
@extends('layouts.admin')

@section('css')
    @parent

    <!-- Select2 -->
    {{--<link rel="stylesheet" href="{{ asset('adminZone/plugins/select2/css/select2.min.css') }}">--}}
    {{--<link rel="stylesheet" href="{{ asset('adminZone/plugins/select2-bootstrap4-theme/select2-bootstrap4.min.css') }}">--}}

@endsection

@section('breadcrumb')
    <!-- Content Header (Page header) -->
    <section class="content-header">
        <div class="container-fluid">
            <div class="row mb-2">
                <div class="col-sm-6">
                    <h1>{{ $titlePage }}</h1>
                </div>
                <div class="col-sm-6">
                    <ol class="breadcrumb float-sm-right">
                        <li class="breadcrumb-item"><a href="{{ route('admin') }}">Página Principal</a></li>
                        <li class="breadcrumb-item"><a href="{{ route('menus.index') }}">Menús</a></li>
                        <li class="breadcrumb-item active">{{ $title }}</li>
                    </ol>
                </div>
            </div>
        </div><!-- /.container-fluid -->
    </section>
@endsection

@section('contenido')

    @if($errors->any())

        <div class="alert alert-danger alert-dismissible">
            <button type="button" class="close" data-dismiss="alert" aria-hidden="true">×</button>
            <h5><i class="icon fas fa-ban"></i> Alert!</h5>
            @foreach ($errors->all() as $error)
                <li>{{ $error }}</li>
            @endforeach
        </div>

    @endif

    <div class="card">

        {!! Form::open(['route' => 'menus.store', 'autocomplete' => 'off']) !!}

        @php $edit = 0; @endphp
        @include('admin.menus.partials.form')

        <div class="card-footer">
            {!! Form::submit('Crear Menú', ['class' => 'btn btn-primary'])!!}

            <a class="btn btn-link" href="{{ url()->previous() }}">{{ __('Volver') }}</a>
        </div>

        {!! Form::close() !!}

    </div>
@endsection

resources/views/admin/menus/edit.blade.php
<?php
/**
 * Created by PhpStorm.
 * User: Starglob2
 * Date: 24/05/2021
 * Time: 16:48
 */
?>

@extends('layouts.admin')

@section('css')
    @parent

    <!-- Select2 -->
    {{--<link rel="stylesheet" href="{{ asset('adminZone/plugins/select2/css/select2.min.css') }}">--}}
    {{--<link rel="stylesheet" href="{{ asset('adminZone/plugins/select2-bootstrap4-theme/select2-bootstrap4.min.css') }}">--}}

@endsection

@section('breadcrumb')
    <!-- Content Header (Page header) -->
    <section class="content-header">
        <div class="container-fluid">
            <div class="row mb-2">
                <div class="col-sm-6">
                    <h1>{{ $titlePage }}</h1>
                </div>
                <div class="col-sm-6">
                    <ol class="breadcrumb float-sm-right">
                        <li class="breadcrumb-item"><a href="{{ route('admin') }}">Página Principal</a></li>
                        <li class="breadcrumb-item"><a href="{{ route('menus.index') }}">Menús</a></li>
                        <li class="breadcrumb-item active">{{ $title }}</li>
                    </ol>
                </div>
            </div>
        </div><!-- /.container-fluid -->
    </section>
@endsection

@section('contenido')

    @if($errors->any())

        <div class="alert alert-danger alert-dismissible">
            <button type="button" class="close" data-dismiss="alert" aria-hidden="true">×</button>
            <h5><i class="icon fas fa-ban"></i> Alert!</h5>
            @foreach ($errors->all() as $error)
                <li>{{ $error }}</li>
            @endforeach
        </div>

    @endif

    <div class="card">

        {{--@php echo $menu; @endphp--}}

        {!! Form::model($menu,['route' => ['menus.update', $menu], 'autocomplete' => 'off', 'method' => 'put']) !!}

            @php $edit = 1; @endphp
            @include('admin.menus.partials.form')

        <div class="card-footer">
            {!! Form::submit('Editar Menú', ['class' => 'btn btn-primary'])!!}

            <a class="btn btn-link" href="{{ url()->previous() }}">{{ __('Volver') }}</a>
        </div>

        {!! Form::close() !!}

    </div>

@endsection

resources/views/admin/menus/index.blade.php
<?php
/**
 * Created by PhpStorm.
 * User: Starglob2
 * Date: 22/04/2021
 * Time: 12:01
 */
?>
@extends('layouts.admin')

@section('breadcrumb')
    <!-- Content Header (Page header) -->
    <section class="content-header">
        <div class="container-fluid">
            <div class="row mb-2">
                <div class="col-sm-6">
                    <h1>{{ $titlePage }}</h1>
                </div>
                <div class="col-sm-6">
                    <ol class="breadcrumb float-sm-right">
                        <li class="breadcrumb-item"><a href="{{ route('admin') }}">Página Principal</a></li>
                        <li class="breadcrumb-item active">{{ $title }}</li>
                    </ol>
                </div>
            </div>
        </div><!-- /.container-fluid -->
    </section>
@endsection

@section('contenido')

    <div class="row">

        <div class="col-lg-12">

            <div class="panel-body">

                @if(Session::has('info'))
                    <div class="alert alert-info" role="alert">
                        <strong>{{ Session::get('info') }}</strong>
                    </div>
                @endif

                @if($menus->isEmpty())
                    <div class="alert alert-warning alert-dismissible">
                        <button type="button" class="close" data-dismiss="alert" aria-hidden="true">×</button>
                        <h4><i class="fas fa-exclamation-triangle"></i> ¡Atención!</h4>
                        No existen datos que mostrar
                    </div>
                    <div class="row">
                        <div class="col-lg-12">
                            <a href="{{ route('menus.create') }}" class="btn btn-success"><i class="fa fa-plus"></i> Nuevo menú</a>
                        </div>
                    </div>
                    <br>

                @else

                    <div class="row">
                        <div class="col-lg-12">
                            <div class="card">

                                <div class="card-header">

                                    <h3 class="card-title">
                                        Listado de Menús
                                    </h3>

                                    <div>
                                        <a href="{{ route('menus.create') }}" class="btn btn-warning float-right"><i class="fa fa-plus"></i> Nuevo menú</a>
                                    </div>
                                </div>

                                <div class="card-body">

                                    <form action="{{ route('menus.index') }}" method="GET" role="search" autocomplete="off">
                                        @csrf
                                        <div class="input-group">
                                            <input type="text" class="form-control" name="term" placeholder="Introduzca el nombre de un plato" id="term">

                                            <div class="input-group-btn mr-3">
                                                <button class="btn btn-outline-dark" type="submit" title="Buscar platos">
                                                    <span class="fas fa-search"></span>
                                                </button>
                                            </div>
                                            <a href="{{ route('menus.index') }}">
                                                    <span class="input-group-btn">
                                                    <button class="btn btn-outline-success" type="button" title="Actualizar página">
                                                       <span class="fas fa-sync-alt"></span>
                                                    </button>
                                                    </span>
                                            </a>
                                        </div>
                                    </form>
                                    <br>

                                    {{--<div class="table-responsive">--}}

                                    {{--<table class="table table-striped table-bordered table-hover">--}}
                                    <table class="table table-striped">
                                        <thead>
                                        <tr>
                                            <th>ID</th>
                                            <th>Tipo de menú</th>
                                            <th>Categorías</th>
                                            <th>Platos</th>
                                            <th>Descripción</th>
                                            <th>Precio</th>
                                            <th>Fecha</th>
                                            <th colspan="2">Acciones</th>
                                        </tr>
                                        </thead>
                                        <tbody>
                                        @foreach($menus as $menu)
                                            <tr>
                                                <td>{{ $menu->id }}</td>
                                                <td>{{ $menu->type->name }}</td>
                                                <td>@php $name= " "; foreach($menu->categories as $category){ if($category->name <> $name) echo $category->name; echo "<br>";   $name=$category->name;} @endphp  </td>
                                                <td>@foreach($menu->dishes as $dish)  {{ $dish->name }} <br> @endforeach</td>

                                                <td style="width: 15%;">{{ $menu->description }}</td>
                                                <td>{{ $menu->price }}</td>
                                                {{--<td>{{ date('d/m/Y', strtotime($menu->dateMenu)) }}</td>--}}
                                                <td>@if($menu->dateMenu) {{ date('d/m/Y', strtotime($menu->dateMenu)) }} @endif </td>
                                                {{--<td width="10px">--}}
                                                    {{--<a class="btn btn-primary btn-sm" href="{{ route('menus.show', $menu) }}"><i--}}
                                                    {{--class="fas fa-eye"></i></a>--}}
                                                {{--</td>--}}
                                                <td width="10px">
                                                    <a class="btn btn-secondary btn-sm" href="{{ route('menus.edit', $menu->id) }}" title="Editar"><i
                                                                class="fas fa-pen"></i></a>
                                                </td>
                                                <td width="10px">
                                                    <a class="btn btn-danger btn-sm" title="Eliminar" data-toggle="modal"
                                                       data-target="#modalEliminar" data-href="{{ route('menus.destroy', $menu->id) }}"
                                                       href='#'><i class='fa fa-trash'></i></a>

                                                </td>
                                            </tr>
                                        @endforeach

                                        </tbody>
                                        <tfoot>
                                        <tr>
                                            <th>ID</th>
                                            <th>Tipo de menú</th>
                                            <th>Categorías</th>
                                            <th>Platos</th>
                                            <th>Descripción</th>
                                            <th>Precio</th>
                                            <th>Fecha</th>
                                            <th colspan="2">Acciones</th>
                                        </tr>
                                        </tfoot>
                                    </table>

                                    {{--</div>--}}

                                </div>

                                <div class="card-footer d-flex justify-content-center">

                                    {{ $menus->links() }}

                                </div>

                            </div>

                        </div>

                    </div>
                @endif

            </div>

        </div>
    </div>

@endsection


@section('modalEliminar')

    <!-- Dialogo modal eliminar -->

    <div class="modal modal-danger fade" id="modalEliminar" name="modalEliminar" tabindex="-1" role="dialog"
         aria-labelledby="myModalLabel">
        <div class="modal-dialog" role="document">
            <div class="modal-content bg-danger">
                <div class="modal-header" id="titl">
                    <h4 class="modal-title" id="titleModalEliminar">¡Eliminar Menú!</h4>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span
                                aria-hidden="true">&times;</span></button>
                </div>
                <div class="modal-body">
                    <h5 style="font-family:Verdana; font-size: 14px;" id="bodyModalEliminar" class="debug-url">
                        ¿Está seguro de que desea eliminar el plato?
                    </h5>
                    <form action="" class="form-modal" method="POST">
                        @method('DELETE')
                        @csrf
                    </form>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-outline-light" data-dismiss="modal">Cancelar</button>
                    <button type="button" class="btn btn-outline-light btn-ok">Eliminar</button>
                </div>
            </div>
        </div>
    </div>
@endsection

@section('scripts')
    @parent

    {{--<!-- DataTables -->--}}
    {{--<script src="{{ asset('plugins/datatables/jquery.dataTables.js') }}"></script>--}}
    {{--<script src="{{ asset('plugins/datatables-bs4/js/dataTables.bootstrap4.js') }}"></script>--}}

    {{--<!-- page script -->--}}
    {{--<script>--}}
    {{--$(function () {--}}
    {{--$('#categories').DataTable({});--}}
    {{--});--}}
    {{--</script>--}}

    <!-- Modal Eliminar -->
    <script>
        $('#modalEliminar').on('show.bs.modal', function (e) {
            $(this).find('.form-modal').attr('action', $(e.relatedTarget).data('href'));
            $(this).find('.btn-ok').click(function () {
                $("form").submit();
            });
        });
    </script>

@endsection

resources/views/admin/menus/selectDishes.blade.php
<?php
/**
 * Created by PhpStorm.
 * User: Starglob2
 * Date: 24/05/2021
 * Time: 10:35
 */
?>

@extends('layouts.admin')

@section('css')
    @parent

    <!-- Select2 -->
    <link rel="stylesheet" href="{{ asset('adminZone/plugins/select2/css/select2.min.css') }}">
    <link rel="stylesheet" href="{{ asset('adminZone/plugins/select2-bootstrap4-theme/select2-bootstrap4.min.css') }}">

@endsection

@section('breadcrumb')
    <!-- Content Header (Page header) -->
    <section class="content-header">
        <div class="container-fluid">
            <div class="row mb-2">
                <div class="col-sm-6">
                    <h1>{{ $titlePage }}</h1>
                </div>
                <div class="col-sm-6">
                    <ol class="breadcrumb float-sm-right">
                        <li class="breadcrumb-item"><a href="{{ route('admin') }}">Página Principal</a></li>
                        <li class="breadcrumb-item"><a href="{{ route('menus.create') }}">Crear menú</a></li>
                        <li class="breadcrumb-item active">{{ $title }}</li>
                    </ol>
                </div>
            </div>
        </div><!-- /.container-fluid -->
    </section>
@endsection

@section('contenido')

    @if($errors->any())

        <div class="alert alert-danger alert-dismissible">
            <button type="button" class="close" data-dismiss="alert" aria-hidden="true">×</button>
            <h5><i class="icon fas fa-ban"></i> Alert!</h5>
            @foreach ($errors->all() as $error)
                <li>{{ $error }}</li>
            @endforeach
        </div>

    @endif

    <div class="card">

        {!! Form::open(['route' => 'menus.storeDish', 'autocomplete' => 'off']) !!}

        {{--@php $actualizar = 0; @endphp--}}
        @include('admin.menus.partials.form-dishes')

        <div class="card-footer">
            {!! Form::submit('Guardar Platos del Menú', ['class' => 'btn btn-primary'])!!}

            <a class="btn btn-link" href="{{ url()->previous() }}">{{ __('Volver') }}</a>
        </div>

        {!! Form::close() !!}

    </div>
@endsection