routes/web.php
<?php

use App\Http\Controllers\Admin\AllergenController;
use App\Http\Controllers\Admin\CategoryController;
use App\Http\Controllers\Admin\DishController;
use App\Http\Controllers\Admin\MenuController;
use App\Http\Controllers\Admin\TypeController;
use App\Http\Controllers\PublicController;
use Illuminate\Support\Facades\Route;

use App\Http\Controllers\Admin\AdminController;


/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

// PARTE PÚBLICA

/*
 * HOME
 */

//Route::get('/', function () {
//    $title = "Inicio";
//    return view('home', compact('title'));
//})->name('home');

Route::get('/', [PublicController::class, 'index'])->name('home');

Route::get('/menu', [PublicController::class, 'menu'])->name('menu');


/*
 * Acceso a Administración
 */
Route::get('login_empresa', function () {
    return view('auth.login');
})->name('login_empresa');


//Auth::routes();

// PARTE ADMINISTRACIÓN

Route::middleware(['auth:sanctum', 'verified'])->get('/dashboard', function () {
    return view('dashboard');
})->name('dashboard');


Route::group(['middleware' => ['auth']], function () {

    Route::get('admin/printMDia', [AdminController::class, 'printMDia'])->name('admin.printMDia');
    Route::get('admin/printMDegus', [AdminController::class, 'printMDegus'])->name('admin.printMDegus');

    Route::get('/admin', [AdminController::class, 'index'])->name('admin');

    Route::resource('/admin/allergens', AllergenController::class);

    Route::resource('/admin/categories', CategoryController::class);

    Route::resource('/admin/types', TypeController::class);

    Route::resource('/admin/dishes', DishController::class);

    //Route::get('menus/selectDishes', [MenuController::class, 'selectDishes'])->name('menu.selectDishes');


    Route::post('menus/selectDishes', [MenuController::class, 'storeDish'])->name('menus.storeDish');
    Route::put('menus/updateDishes', [MenuController::class, 'updateDish'])->name('menus.updateDish');

    Route::resource('/admin/menus', MenuController::class);


});

app/Models/Allergen.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Allergen extends Model
{
    use HasFactory;

    protected $fillable = ['name', 'description'];

    //aquí guardamos los campos que queremos evitar que se llenen por asignación masiva
    //protected $guarded = ['id', 'created_at', 'updated_at'];

    //Relación muchos a muchos

    public function dishes(){
        return $this->belongsToMany(Dish::class);
    }

    //Relación uno a uno polimórfica

    public function image(){
        return $this->morphOne(Image::class, 'imageable');
    }

}

app/Http/Controllers/Admin/AllergenController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use App\Models\Allergen;
use App\Models\Image;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Storage;

class AllergenController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index(Request $request)
    {
        $titlePage = "Gestión de Alérgenos";
        $title = "Alérgenos";

        $allergens = Allergen::where([
            [function ($query) use ($request){
                if(($term = $request->term)) {
                    $query->orWhere('name', 'LIKE', '%'. $term . '%')->get();
                }
            }]
        ])
            ->paginate(5);

        return view('admin.allergens.index', compact('allergens', 'titlePage', 'title'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $titlePage = "Creación de Alérgenos";
        $title = "Crear alérgeno";

        return view('admin.allergens.create', compact('titlePage', 'title'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $request->validate([
            'name' => 'required',
            'description' => 'required'
        ]);

        $allergen = new Allergen();
        $img = new Image();

        //Allergen::create($request->all());
        $allergen->name = $request->name;
        $allergen->description = $request->description;

        $allergen->save();

        if ($request->file('file')){
            $url = Storage::put('allergens', $request->file('file'));
            $alternativeText = $request->alternativeText;

            $allergen->image()->create([
                'url' => $url,
                'alternativeText' => $alternativeText
            ]);
        }

        return redirect()->route('allergens.index')
            ->with('info', 'Alérgeno creado con éxito.');
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Models\Allergen  $allergen
     * @return \Illuminate\Http\Response
     */
    public function show(Allergen $allergen)
    {
        $titlePage = "Mostrar detalle de Alérgeno";
        return view('admin.allergens.show', compact('allergen', 'titlePage'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Models\Allergen  $allergen
     * @return \Illuminate\Http\Response
     */
    public function edit(Allergen  $allergen)
    {
        $titlePage = "Editar Alérgeno";
        $title = "Alérgenos";

        return view('admin.allergens.edit', compact('allergen', 'titlePage', 'title'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Models\Allergen $allergen
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Allergen $allergen)
    {
        $request->validate([
            'name' => 'required',
            'description' => 'required'
        ]);

        //Allergen::create($request->all());
        $allergen->name = $request->name;
        $allergen->description = $request->description;

        $allergen->save();

        if ($request->file('file')){
            $url = Storage::put('allergens', $request->file('file'));
            $alternativeText = $request->alternativeText;

            if($allergen->image){ //si tiene asociada una imagen
                Storage::delete($allergen->image->url);

                $allergen->image()->update([
                    'url' => $url,
                    'alternativeText' => $alternativeText
                ]);

            }else{
                $allergen->image()->create([
                    'url' => $url,
                    'alternativeText' => $alternativeText
                ]);
            }
        }

        return redirect()->route('allergens.index')
            ->with('info', 'Alérgeno actualizado con éxito.');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Models\Allergen $allergen
     * @return \Illuminate\Http\Response
     */
    public function destroy(Allergen $allergen)
    {
        try {
            $allergen->delete();
        } catch (\Exception $e) {
            echo $e->getMessage();
        }

        return redirect()->route('allergens.index')
            ->with('info', 'Alérgeno eliminado con éxito.');
    }
}

resources/views/admin/allergens/create.blade.php
<?php
/**
 * Created by PhpStorm.
 * User: Starglob2
 * Date: 22/04/2021
 * Time: 12:38
 */
?>
@extends('layouts.admin')

@section('breadcrumb')
    <!-- Content Header (Page header) -->
    <section class="content-header">
        <div class="container-fluid">
            <div class="row mb-2">
                <div class="col-sm-6">
                    <h1>{{ $titlePage }}</h1>
                </div>
                <div class="col-sm-6">
                    <ol class="breadcrumb float-sm-right">
                        <li class="breadcrumb-item"><a href="{{ route('admin') }}">Página Principal</a></li>
                        <li class="breadcrumb-item"><a href="{{ route('allergens.index.index') }}">Alérgenos</a></li>
                        <li class="breadcrumb-item active">{{ $title }}</li>
                    </ol>
                </div>
            </div>
        </div><!-- /.container-fluid -->
    </section>
@endsection

@section('contenido')

    @if($errors->any())

        <div class="alert alert-danger alert-dismissible">
            <button type="button" class="close" data-dismiss="alert" aria-hidden="true">×</button>
            <h5><i class="icon fas fa-ban"></i> Alert!</h5>
            @foreach ($errors->all() as $error)
                <li>{{ $error }}</li>
            @endforeach
        </div>

    @endif

    <div class="card">
        {{--<form role="form" method="post" action="{{ route('allergens.store') }}">--}}
            {{--@method('PUT')--}}
            {{--@csrf--}}


        {{--</form>--}}

        {{-- Para enviar archivos, en este caso imágenes, activamos el parámetro 'files' en el formulario --}}
        {!! Form::open(['route' => 'allergens.store', 'autocomplete' => 'off', 'files' => true]) !!}

        @include('admin.allergens.partials.form')

        <div class="card-footer">
            {{--<button type="submit" class="btn btn-primary">{{ __('Crear Alérgeno') }}</button>--}}
            {!! Form::submit('Crear Alérgeno', ['class' => 'btn btn-primary'])!!}

            <a class="btn btn-link" href="{{ url()->previous() }}">{{ __('Volver') }}</a>
        </div>

        {!! Form::close() !!}

    </div>
@endsection

resources/views/admin/allergens/edit.blade.php
<?php
/**
 * Created by PhpStorm.
 * User: Starglob2
 * Date: 26/04/2021
 * Time: 19:57
 */
?>
@extends('layouts.admin')

@section('breadcrumb')
    <!-- Content Header (Page header) -->
    <section class="content-header">
        <div class="container-fluid">
            <div class="row mb-2">
                <div class="col-sm-6">
                    <h1>{{ $titlePage }}</h1>
                </div>
                <div class="col-sm-6">
                    <ol class="breadcrumb float-sm-right">
                        <li class="breadcrumb-item"><a href="{{ route('admin') }}">Página Principal</a></li>
                        <li class="breadcrumb-item active">{{ $title }}</li>
                    </ol>
                </div>
            </div>
        </div><!-- /.container-fluid -->
    </section>
@endsection

@section('contenido')

    @if($errors->any())

        <div class="alert alert-danger alert-dismissible">
            <button type="button" class="close" data-dismiss="alert" aria-hidden="true">×</button>
            <h5><i class="icon fas fa-ban"></i> Alert!</h5>
            @foreach ($errors->all() as $error)
                <li>{{ $error }}</li>
            @endforeach
        </div>

    @endif

    <div class="card">

        {{--<form role="form" method="post" action="{{ route('allergens.update', $allergen) }}">--}}
        {!! Form::model($allergen,['route' => ['allergens.update', $allergen], 'autocomplete' => 'off', 'files' => true, 'method' => 'put']) !!}

        @include('admin.allergens.partials.form')

        <div class="card-footer">
            {{--<button type="submit" class="btn btn-primary">{{ __('Crear Alérgeno') }}</button>--}}
            {!! Form::submit('Editar Alérgeno', ['class' => 'btn btn-primary'])!!}

            <a class="btn btn-link" href="{{ url()->previous() }}">{{ __('Volver') }}</a>
        </div>

        {!! Form::close() !!}
    </div>
@endsection

resources/views/admin/allergens/index.blade.php
<?php
/**
 * Created by PhpStorm.
 * User: Starglob2
 * Date: 22/04/2021
 * Time: 12:01
 */
?>

@extends('layouts.admin')

@section('breadcrumb')
    <!-- Content Header (Page header) -->
    <section class="content-header">
        <div class="container-fluid">
            <div class="row mb-2">
                <div class="col-sm-6">
                    <h1>{{ $titlePage }}</h1>
                </div>
                <div class="col-sm-6">
                    <ol class="breadcrumb float-sm-right">
                        <li class="breadcrumb-item"><a href="{{ route('admin') }}">Página Principal</a></li>
                        <li class="breadcrumb-item active">{{ $title }}</li>
                    </ol>
                </div>
            </div>
        </div><!-- /.container-fluid -->
    </section>
@endsection

@section('contenido')

    <div class="row">

        <div class="col-lg-12">

            <div class="panel-body">

                @if(Session::has('info'))
                    <div class="alert alert-info" role="alert">
                        <strong>{{ Session::get('info') }}</strong>
                    </div>
                @endif

                @if($allergens->isEmpty())
                    <div class="alert alert-warning alert-dismissible">
                        <button type="button" class="close" data-dismiss="alert" aria-hidden="true">×</button>
                        <h4><i class="fas fa-exclamation-triangle"></i> ¡Atención!</h4>
                        No existen datos que mostrar
                    </div>
                    {{--<div class="row">--}}
                        {{--<div class="col-lg-12">--}}
                            {{--<a href="{{ route('allergens.create') }}" class="btn btn-success"><i class="fa fa-plus"></i> Nuevo alérgeno</a>--}}
                        {{--</div>--}}
                    {{--</div>--}}
                    <br>

                @else

                    <div class="row">
                        <div class="col-lg-12">
                            <div class="card">

                                <div class="card-header">

                                    <h3 class="card-title">
                                        Listado de Alérgenos
                                    </h3>

                                    {{--<div>--}}
                                        {{--<a href="{{ route('allergens.create') }}" class="btn btn-warning float-right"><i class="fa fa-plus"></i> Nuevo alérgeno</a>--}}
                                    {{--</div>--}}
                                </div>

                                <div class="card-body">

                                    <form action="{{ route('allergens.index') }}" method="GET" role="search" autocomplete="off">
                                        @csrf
                                        <div class="input-group">
                                            <input type="text" class="form-control" name="term" placeholder="Introduzca el nombre de un alérgeno" id="term">

                                            <div class="input-group-btn mr-3">
                                                <button class="btn btn-outline-dark" type="submit" title="Buscar alérgenos">
                                                    <span class="fas fa-search"></span>
                                                </button>
                                            </div>
                                            <a href="{{ route('allergens.index') }}">
                                                    <span class="input-group-btn">
                                                    <button class="btn btn-outline-success" type="button" title="Actualizar página">
                                                       <span class="fas fa-sync-alt"></span>
                                                    </button>
                                                    </span>
                                            </a>
                                        </div>
                                    </form>
                                    <br>

                                    {{--<div class="table-responsive">--}}

                                    {{--<table class="table table-striped table-bordered table-hover">--}}
                                    <table class="table table-striped">
                                        <thead>
                                        <tr>
                                            <th>ID</th>
                                            <th>Nombre</th>
                                            <th>Descripción</th>
                                            <th>Imagen</th>
                                            {{--<th colspan="2">Acciones</th>--}}
                                        </tr>
                                        </thead>
                                        <tbody>
                                        @foreach($allergens as $allergen)
                                            <tr>
                                                <td>{{ $allergen->id }}</td>
                                                <td>{{ $allergen->name }}</td>
                                                {{--<td width="60%">{{ $allergen->description }}</td>--}}
                                                <td width="70%">{{ $allergen->description }}</td>
                                                <td>@if($allergen->image)
                                                        <img id="picture" src="{{ Storage::url($allergen->image->url) }}" alt="{{ $allergen->image->alternativeText }}" width="50%">
                                                    @else
                                                        <img id="picture" src="https://cdn.pixabay.com/photo/2015/03/25/13/04/page-not-found-688965_960_720.png" alt="No has cargado ninguna imagen" width="20%">
                                                    @endif
                                                </td>
                                                {{--<td width="10px">--}}
                                                    {{--<a class="btn btn-secondary btn-sm" href="{{ route('allergens.edit', $allergen) }}" title="Editar"><i--}}
                                                                {{--class="fas fa-pen"></i></a>--}}
                                                {{--</td>--}}
                                                {{--<td width="10px">--}}
                                                    {{--<a class="btn btn-danger btn-sm" title="Eliminar" data-toggle="modal"--}}
                                                       {{--data-target="#modalEliminar" data-href="{{ route('allergens.destroy', $allergen) }}"--}}
                                                       {{--href='#'><i class='fa fa-trash'></i></a>--}}

                                                {{--</td>--}}
                                            </tr>
                                        @endforeach

                                        </tbody>
                                        <tfoot>
                                        <tr>
                                            <th>ID</th>
                                            <th>Nombre</th>
                                            <th>Descripción</th>
                                            {{--<th colspan="3">Acciones</th>--}}
                                        </tr>
                                        </tfoot>
                                    </table>

                                    {{--</div>--}}

                                </div>

                                <div class="card-footer d-flex justify-content-center">

                                    {{ $allergens->links() }}

                                </div>

                            </div>

                        </div>

                    </div>
                @endif

            </div>

        </div>
    </div>

@endsection


@section('modalEliminar')

    <!-- Dialogo modal eliminar -->

    <div class="modal modal-danger fade" id="modalEliminar" name="modalEliminar" tabindex="-1" role="dialog"
         aria-labelledby="myModalLabel">
        <div class="modal-dialog" role="document">
            <div class="modal-content bg-danger">
                <div class="modal-header" id="titl">
                    <h4 class="modal-title" id="titleModalEliminar">¡Eliminar Alérgeno!</h4>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span
                                aria-hidden="true">&times;</span></button>
                </div>
                <div class="modal-body">
                    <h5 style="font-family:Verdana; font-size: 14px;" id="bodyModalEliminar" class="debug-url">
                        ¿Está seguro de que desea eliminar el alérgeno?
                    </h5>
                    <form action="" class="form-modal" method="POST">
                        @method('DELETE')
                        @csrf
                    </form>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-outline-light" data-dismiss="modal">Cancelar</button>
                    <button type="button" class="btn btn-outline-light btn-ok">Eliminar</button>
                </div>
            </div>
        </div>
    </div>
@endsection

@section('scripts')
    @parent

    {{--<!-- DataTables -->--}}
    {{--<script src="{{ asset('plugins/datatables/jquery.dataTables.js') }}"></script>--}}
    {{--<script src="{{ asset('plugins/datatables-bs4/js/dataTables.bootstrap4.js') }}"></script>--}}

    {{--<!-- page script -->--}}
    {{--<script>--}}
    {{--$(function () {--}}
    {{--$('#categories').DataTable({});--}}
    {{--});--}}
    {{--</script>--}}

    <!-- Modal Eliminar -->
    <script>
        $('#modalEliminar').on('show.bs.modal', function (e) {
            $(this).find('.form-modal').attr('action', $(e.relatedTarget).data('href'));
            $(this).find('.btn-ok').click(function () {
                $("form").submit();
            });
        });
    </script>

@endsection