routes/web.php
<?php

use App\Http\Controllers\Admin\AllergenController;
use App\Http\Controllers\Admin\CategoryController;
use App\Http\Controllers\Admin\DishController;
use App\Http\Controllers\Admin\MenuController;
use App\Http\Controllers\Admin\TypeController;
use App\Http\Controllers\PublicController;
use Illuminate\Support\Facades\Route;

use App\Http\Controllers\Admin\AdminController;


/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

// PARTE PÚBLICA

/*
 * HOME
 */

//Route::get('/', function () {
//    $title = "Inicio";
//    return view('home', compact('title'));
//})->name('home');

Route::get('/', [PublicController::class, 'index'])->name('home');

Route::get('/menu', [PublicController::class, 'menu'])->name('menu');


/*
 * Acceso a Administración
 */
Route::get('login_empresa', function () {
    return view('auth.login');
})->name('login_empresa');


//Auth::routes();

// PARTE ADMINISTRACIÓN

Route::middleware(['auth:sanctum', 'verified'])->get('/dashboard', function () {
    return view('dashboard');
})->name('dashboard');


Route::group(['middleware' => ['auth']], function () {

    Route::get('admin/printMDia', [AdminController::class, 'printMDia'])->name('admin.printMDia');
    Route::get('admin/printMDegus', [AdminController::class, 'printMDegus'])->name('admin.printMDegus');

    Route::get('/admin', [AdminController::class, 'index'])->name('admin');

    Route::resource('/admin/allergens', AllergenController::class);

    Route::resource('/admin/categories', CategoryController::class);

    Route::resource('/admin/types', TypeController::class);

    Route::resource('/admin/dishes', DishController::class);

    //Route::get('menus/selectDishes', [MenuController::class, 'selectDishes'])->name('menu.selectDishes');


    Route::post('menus/selectDishes', [MenuController::class, 'storeDish'])->name('menus.storeDish');
    Route::put('menus/updateDishes', [MenuController::class, 'updateDish'])->name('menus.updateDish');

    Route::resource('/admin/menus', MenuController::class);


});

app/Models/Category.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Category extends Model
{
    use HasFactory;

    protected $fillable = ['name', 'description'];

    //Relación muchos a muchos

    public function dishes(){
        return $this->belongsToMany(Dish::class,'category_dish_menu')
            //->withPivot('menu_id', 'status');
            ->withPivot('menu_id');
    }

    public function menus(){
        return $this->belongsToMany(Menu::class, 'category_dish_menu')
            //->withPivot('dish_id', 'status');
            ->withPivot('dish_id');
    }
}

app/Http/Controllers/Admin/CategoryController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use App\Models\Category;
use Illuminate\Http\Request;

class CategoryController extends Controller
{
    protected $paginationTheme = 'bootstrap';

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index(Request $request)
    {
        $titlePage = "Gestión de Categorías";
        $title = "Categorías";

        $categories = Category::where([
            [function ($query) use ($request){
                if(($term = $request->term)) {
                    $query->orWhere('name', 'LIKE', '%'. $term . '%')->get();
                }
            }]
        ])
            ->paginate(6);

        return view('admin.categories.index', compact('categories', 'titlePage', 'title'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $titlePage = "Creación de Categoría";
        $title = "Crear categoría";

        return view('admin.categories.create', compact('titlePage', 'title'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $request->validate([
            'name' => 'required',
            //'description' => 'required'
        ]);

        Category::create($request->all());

        return redirect()->route('categories.index')
            ->with('info', 'Categoría creada con éxito.');
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Models\Category  $category
     * @return \Illuminate\Http\Response
     */
    public function show(Category $category)
    {
        $titlePage = "Mostrar detalle de Categoría";

        return view('admin.categories.show', compact('category', 'titlePage'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Models\Category  $category
     * @return \Illuminate\Http\Response
     */
    public function edit(Category $category)
    {
        $titlePage = "Editar Categoría";
        $title = "Categorías";

        return view('admin.categories.edit', compact('category', 'titlePage', 'title'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Models\Category  $category
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Category $category)
    {
        $request->validate([
            'name' => 'required',
            //'description' => 'required'
        ]);

        $category->update($request->all());

        return redirect()->route('categories.index')
            ->with('info', 'Categoría actualizada con éxito.');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Models\Category  $category
     * @return \Illuminate\Http\Response
     */
    public function destroy(Category $category)
    {
        try {
            $category->delete();
        } catch (\Exception $e) {
            echo $e->getMessage();
        }

        return redirect()->route('categories.index')
            ->with('info', 'Categoría eliminada con éxito.');
    }

}

resources/views/admin/categories/create.blade.php
<?php
/**
 * Created by PhpStorm.
 * User: Starglob2
 * Date: 22/04/2021
 * Time: 12:38
 */
?>
@extends('layouts.admin')

@section('breadcrumb')
    <!-- Content Header (Page header) -->
    <section class="content-header">
        <div class="container-fluid">
            <div class="row mb-2">
                <div class="col-sm-6">
                    <h1>{{ $titlePage }}</h1>
                </div>
                <div class="col-sm-6">
                    <ol class="breadcrumb float-sm-right">
                        <li class="breadcrumb-item"><a href="{{ route('admin') }}">Página Principal</a></li>
                        <li class="breadcrumb-item active">{{ $title }}</li>
                    </ol>
                </div>
            </div>
        </div><!-- /.container-fluid -->
    </section>
@endsection

@section('contenido')
    <div class="card">

        {!! Form::open(['route' => 'categories.store', 'autocomplete' => 'off']) !!}

        @include('admin.categories.partials.form')

        <div class="card-footer">
            {{--<button type="submit" class="btn btn-primary">{{ __('Crear Alérgeno') }}</button>--}}
            {!! Form::submit('Crear Categoría', ['class' => 'btn btn-primary'])!!}

            <a class="btn btn-link" href="{{ url()->previous() }}">{{ __('Volver') }}</a>
        </div>

        {!! Form::close() !!}
    </div>
@endsection

resources/views/admin/categories/edit.blade.php
<?php
/**
 * Created by PhpStorm.
 * User: Starglob2
 * Date: 26/04/2021
 * Time: 19:57
 */
?>
@extends('layouts.admin')

@section('breadcrumb')
    <!-- Content Header (Page header) -->
    <section class="content-header">
        <div class="container-fluid">
            <div class="row mb-2">
                <div class="col-sm-6">
                    <h1>{{ $titlePage }}</h1>
                </div>
                <div class="col-sm-6">
                    <ol class="breadcrumb float-sm-right">
                        <li class="breadcrumb-item"><a href="{{ route('admin') }}">Página Principal</a></li>
                        <li class="breadcrumb-item active">{{ $title }}</li>
                    </ol>
                </div>
            </div>
        </div><!-- /.container-fluid -->
    </section>
@endsection

@section('contenido')

    @if($errors->any())

        <div class="alert alert-danger alert-dismissible">
            <button type="button" class="close" data-dismiss="alert" aria-hidden="true">×</button>
            <h5><i class="icon fas fa-ban"></i> Alert!</h5>
            @foreach ($errors->all() as $error)
                <li>{{ $error }}</li>
            @endforeach
        </div>

    @endif

    <div class="card">

        {!! Form::model($category,['route' => ['categories.update', $category], 'autocomplete' => 'off', 'method' => 'put']) !!}

        @include('admin.categories.partials.form')

        <div class="card-footer">
            {{--<button type="submit" class="btn btn-primary">{{ __('Crear Alérgeno') }}</button>--}}
            {!! Form::submit('Editar Categoría', ['class' => 'btn btn-primary'])!!}

            <a class="btn btn-link" href="{{ url()->previous() }}">{{ __('Volver') }}</a>
        </div>

        {!! Form::close() !!}
    </div>
@endsection

resources/views/admin/categories/index.blade.php
<?php
/**
 * Created by PhpStorm.
 * User: Starglob2
 * Date: 22/04/2021
 * Time: 12:01
 */
?>

@extends('layouts.admin')

@section('breadcrumb')
    <!-- Content Header (Page header) -->
    <section class="content-header">
        <div class="container-fluid">
            <div class="row mb-2">
                <div class="col-sm-6">
                    <h1>{{ $titlePage }}</h1>
                </div>
                <div class="col-sm-6">
                    <ol class="breadcrumb float-sm-right">
                        <li class="breadcrumb-item"><a href="{{ route('admin') }}">Página Principal</a></li>
                        <li class="breadcrumb-item active">{{ $title }}</li>
                    </ol>
                </div>
            </div>
        </div><!-- /.container-fluid -->
    </section>
@endsection

@section('contenido')

    <div class="row">

        <div class="col-lg-12">

            <div class="panel-body">

                @if(Session::has('info'))
                    <div class="alert alert-info" role="alert">
                        <strong>{{ Session::get('info') }}</strong>
                    </div>
                @endif

                @if($categories->isEmpty())
                    <div class="alert alert-warning alert-dismissible">
                        <button type="button" class="close" data-dismiss="alert" aria-hidden="true">×</button>
                        <h4><i class="fas fa-exclamation-triangle"></i> ¡Atención!</h4>
                        No existen datos que mostrar
                    </div>
                    <div class="row">
                        <div class="col-lg-12">
                            <a href="{{ route('categories.create') }}" class="btn btn-success"><i class="fa fa-plus"></i> Nueva categoría</a>
                        </div>
                    </div>
                    <br>

                @else

                    <div class="row">
                        <div class="col-lg-12">
                            <div class="card">

                                <div class="card-header">

                                    <h3 class="card-title">
                                        Listado de Categorías
                                    </h3>

                                    <div>
                                        <a href="{{ route('categories.create') }}" class="btn btn-warning float-right"><i class="fa fa-plus"></i> Nueva categoría</a>
                                    </div>
                                </div>

                                <div class="card-body">

                                    <form action="{{ route('categories.index') }}" method="GET" role="search" autocomplete="off">
                                        @csrf
                                        <div class="input-group">
                                            <input type="text" class="form-control" name="term" placeholder="Introduzca el nombre de una categoría" id="term">

                                            <div class="input-group-btn mr-3">
                                                <button class="btn btn-outline-dark" type="submit" title="Buscar categorías">
                                                    <span class="fas fa-search"></span>
                                                </button>
                                            </div>
                                            <a href="{{ route('categories.index') }}">
                                                    <span class="input-group-btn">
                                                    <button class="btn btn-outline-success" type="button" title="Actualizar página">
                                                       <span class="fas fa-sync-alt"></span>
                                                    </button>
                                                    </span>
                                            </a>
                                        </div>
                                    </form>
                                    <br>

                                    {{--<table class="table table-striped table-bordered table-hover">--}}
                                    <table class="table table-striped">
                                        <thead>
                                        <tr>
                                            <th>ID</th>
                                            <th>Nombre</th>
                                            <th>Descripción</th>
                                            {{--<th>Acciones</th>--}}
                                            <th colspan="2">Acciones</th>
                                        </tr>
                                        </thead>
                                        <tbody>
                                        @foreach($categories as $category)
                                            <tr>
                                                <td>{{ $category->id }}</td>
                                                <td>{{ $category->name }}</td>
                                                <td>{{ $category->description }}</td>
                                                <td width="10px">
                                                    <a class="btn btn-secondary btn-sm" href="{{ route('categories.edit', $category) }}" title="Editar"><i
                                                                class="fas fa-pen"></i></a>
                                                </td>
                                                <td width="10px">
                                                    <a class="btn btn-danger btn-sm" title="Eliminar" data-toggle="modal"
                                                       data-target="#modalEliminar" data-href="{{ route('categories.destroy', $category) }}"
                                                       href='#'><i class='fa fa-trash'></i></a>

                                                </td>
                                            </tr>
                                        @endforeach

                                        </tbody>
                                        <tfoot>
                                        <tr>
                                            <th>ID</th>
                                            <th>Nombre</th>
                                            <th>Descripción</th>
                                            <th colspan="3">Acciones</th>
                                        </tr>
                                        </tfoot>
                                    </table>

                                    {{--</div>--}}

                                </div>

                                <div class="card-footer d-flex justify-content-center">

                                    {{ $categories->links() }}

                                </div>

                            </div>

                        </div>

                    </div>
                @endif

            </div>

        </div>
    </div>

@endsection


@section('modalEliminar')

    <!-- Dialogo modal eliminar -->

    <div class="modal modal-danger fade" id="modalEliminar" name="modalEliminar" tabindex="-1" role="dialog"
         aria-labelledby="myModalLabel">
        <div class="modal-dialog" role="document">
            <div class="modal-content bg-danger">
                <div class="modal-header" id="title">
                    <h4 class="modal-title" id="titleModalEliminar">¡Eliminar Categoría!</h4>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span
                                aria-hidden="true">&times;</span></button>
                </div>
                <div class="modal-body">
                    <h5 style="font-family:Verdana; font-size: 14px;" id="bodyModalEliminar" class="debug-url">
                        ¿Está seguro de que desea eliminar la categoría?
                    </h5>
                    <form action="" class="form-modal" method="POST">
                        @method('DELETE')
                        @csrf
                    </form>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-outline-light" data-dismiss="modal">Cancelar</button>
                    <button type="button" class="btn btn-outline-light btn-ok">Eliminar</button>
                </div>
            </div>
        </div>
    </div>
@endsection

@section('scripts')
    @parent

    <!-- Modal Eliminar -->
    <script>
        $('#modalEliminar').on('show.bs.modal', function (e) {
            $(this).find('.form-modal').attr('action', $(e.relatedTarget).data('href'));
            $(this).find('.btn-ok').click(function () {
                $("form").submit();
            });
        });
    </script>

@endsection